mutation UpdateUser(
  $toUpdate: String!
  $currentPassword: String!
  $password: String
) {
  updateUser(
    toUpdate: $toUpdate
    currentPassword: $currentPassword
    password: $password
  ) {
    ... on User {
      __typename
    }
    ... on ErrorResponse {
      __typename
      title
      message
    }
  }
}
