FROM ubuntu:22.04
USER root
RUN apt-get update && apt-get upgrade -y

RUN apt-get install sudo -y
RUN apt-get install git -y
RUN apt-get install zsh -y
RUN apt-get install curl -y

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
RUN apt-get install nodejs -y

RUN useradd -m -G sudo -s /usr/bin/zsh app 
RUN echo "app  ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/app

WORKDIR /home/app/ecart-seller-frontend
USER app 
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
USER app 
ADD . .
