mutation CreateUser(
  $firstName: String!
  $lastName: String!
  $email: String!
  $password: String!
) {
  createUser(
    firstName: $firstName
    lastName: $lastName
    email: $email
    password: $password
  ) {
    ... on Token {
      __typename
      token
    }
    ... on Error {
      __typename
      message
    }
  }
}
