mutation DeleteUser($currentPassword: String!) {
  deleteUser(currentPassword: $currentPassword) {
    ... on SuccessResponse {
      message
    }
    ... on TokenError {
      type
      message
    }
    ... on DeleteUserCredentialError {
      message
    }
  }
}
