mutation Mutation($email: String!, $password: String!) {
  createSession(email: $email, password: $password) {
    ... on AccessToken {
      __typename
      token
    }
    ... on ErrorResponse {
      __typename
      title
      message
    }
  }
}
