mutation Mutation($email: String!, $password: String!) {
  createSession(email: $email, password: $password) {
    ... on User {
      __typename
    }
    ... on ErrorResponse {
      __typename
      title
      message
    }
  }
}
