query ReadUserFirstNameAndPicture {
  readUser {
    ... on User {
      __typename
      firstName
      picture
    }
    ... on ErrorResponse {
      __typename
      title
      message
    }
  }
}
