mutation CreateUser($name: String!, $email: String!, $password: String!) {
  createUser(name: $name, email: $email, password: $password) {
    ... on User {
      name
      email
    }
    ... on ErrorResponse {
      title
      message
    }
  }
}
