mutation CreateUser($name: String!, $email: String!, $password: String!) {
  createUser(name: $name, email: $email, password: $password) {
    ... on AccessToken {
      __typename
      token
    }
    ... on ErrorResponse {
      __typename
      title
      message
    }
  }
}
