mutation UpdateUserPassword($currentPassword: String!, $password: String!) {
  updateUserPassword(currentPassword: $currentPassword, password: $password) {
    ... on TokenError {
      type
      message
    }
    ... on UpdateUserPasswordCredentialError {
      field
      message
    }
    ... on UpdateUserPasswordSuccessResponse {
      message
    }
    ... on UpdateUserInvalidUserCredentialError {
      message
    }
  }
}
