query ReadUser {
  readUser {
    ... on User {
      __typename
      firstName
      lastName
      email
      picture
    }
    ... on TokenError {
      __typename
      type
      message
    }
  }
}
